/**
 * Format time for display
 * @param {Date} date
 */
export function formatTime(date) {
	return date.toLocaleTimeString('en-US', {
		hour: 'numeric',
		minute: '2-digit',
		second: '2-digit', // Add this line to show seconds
		hour12: true
	});
}

// Get status for arrival or departure
export function formatArrivalStatus(predictedTime, scheduledTime) {
	const now = new Date();
	const predicted = new Date(predictedTime);
	const scheduled = new Date(scheduledTime);

	const predictedDiff = Math.floor((predicted - now) / 60000);
	const scheduledDiff = Math.floor((scheduled - now) / 60000);

	if (predictedTime === 0) {
		// No predicted time, use scheduled time
		if (scheduledDiff <= 10) {
			return {
				status: 'Arriving',
				text: 'Arriving in',
				color: 'text-blue-500',
				minutes: scheduledDiff,
				displayTime: formatTime2(scheduledTime)
			};
		} else {
			return {
				status: 'Scheduled',
				text: '',
				color: 'text-gray-500',
				minutes: null,
				displayTime: formatTime2(scheduledTime)
			};
		}
	} else if (predictedDiff < -2) {
		// If the bus left more than 2 minutes ago, it's already gone
		return null;
	} else if (predictedDiff <= 0) {
		// If it's within 2 minutes of departure, show "Departing now"
		return {
			status: 'Departing',
			text: 'Departing now',
			color: 'text-red-500',
			minutes: null,
			displayTime: formatTime2(predictedTime)
		};
	} else if (predictedDiff < 10) {
		// Within 10 minutes
		return {
			status: 'Arriving',
			text: 'Arriving in',
			color: 'text-blue-500',
			minutes: predictedDiff,
			displayTime: formatTime2(predictedTime)
		};
	} else {
		// More than 10 minutes away -> show time only
		return {
			status: 'Scheduled',
			text: '',
			color: 'text-gray-500',
			minutes: null,
			displayTime: formatTime2(predictedTime)
		};
	}
}

// Is the vehicle is early or late?
export function formatRouteStatus(predictedTime, scheduledTime) {
	if (typeof predictedTime === 'undefined' || predictedTime === null || predictedTime === 0) {
		return {
			status: null,
			color: 'gray'
		};
	}

	const predicted = new Date(predictedTime);
	const scheduled = new Date(scheduledTime);
	const diff = Math.floor((predicted - scheduled) / 60000);

	if (diff < -1) {
		return {
			status: `${Math.abs(diff)} min early`,
			color: 'red'
		};
	} else if (diff > 1) {
		return {
			status: `${diff} min late`,
			color: 'blue'
		};
	} else {
		return {
			status: null,
			color: 'gray'
		};
	}
}

/**
 * Format time for display
 * @param {Date} time
 */
export function formatTime2(time) {
	const date = new Date(time);
	return date.toLocaleTimeString('en-US', {
		hour: 'numeric',
		minute: '2-digit',
		hour12: true
	});
}

/**
 * Format date for display
 * @param {Date} date
 */
export function formatDate(date) {
	return date.toLocaleDateString('en-US', {
		weekday: 'long',
		month: 'long',
		day: 'numeric'
	});
}

/**
 * Format the current time for display
 * @param {Date} date
 */
export function formatCurrentTime(date) {
	return date.toLocaleTimeString('en-US', {
		hour: '2-digit',
		minute: '2-digit',
		second: '2-digit',
		hour12: true
	});
}

/**
 * Generate a unique ID string based on trip and stop IDs.
 * Used to uniquely identify departure blocks.
 *
 * @param {string} tripID - The trip ID
 * @param {string} stopID - The stop ID
 * @returns {string} - A unique ID in the format "tripID-stopID-randomNumber"
 */
export function generateRandomID(tripID, stopID) {
	return `${tripID ?? '0'}-${stopID ?? '0'}-${Math.floor(Math.random() * 10000)}`;
}

/**
 * Sort a list of departures by their earliest available departure time.
 * Filters out departures with invalid or missing times.
 *
 * @param {Array} departures - Array of departure objects with predicted or scheduled times
 * @returns {Array} - Sorted array of valid departures in chronological order
 */
export function sortEarliestDepartures(departures) {
	const validDepartures = departures.filter((dep) => {
		const time = dep.predictedDepartureTime ?? dep.scheduledDepartureTime;

		return time && time > 0;
	});

	const sortedDepartures = validDepartures.sort((x, y) => {
		const timeX = x.predictedDepartureTime ?? x.scheduledDepartureTime;
		const timeY = y.predictedDepartureTime ?? y.scheduledDepartureTime;

		return timeX - timeY;
	});

	return sortedDepartures;
}

/**
 * Converts a Unix timestamp (in milliseconds) to a human-readable date and time string.
 *
 * @param {number} timestamp - The Unix timestamp in milliseconds (i.e. 1750530360000)
 * @returns {string} - A formatted date string like "Mon, Jul 21, 2025"
 */
export function formatTimestamp(timestamp) {
	return new Date(timestamp).toLocaleString('en-US', {
		weekday: 'short',
		year: 'numeric',
		month: 'short',
		day: 'numeric'
	});
}

/**
 * Validates if a string is in the expected formatted timestamp format.
 * Assumes the string was generated by `formatTimestamp()`
 *
 * @param {string} str - The formatted date string to validate
 * @returns {boolean} - True if valid date, false otherwise
 */
export function validateTimestamp(str) {
	const parsedDate = new Date(str);

	return !isNaN(parsedDate.getTime()) && typeof str === 'string' && str.trim().length > 0;
}
